//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Rental_Tri.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Movie
    {
        public int Movie_ID { get; set; }
        public string Movie_Title { get; set; }
        public string Movie_Description { get; set; }
        public Nullable<bool> IsRented { get; set; }
        public Nullable<System.DateTime> Rental_Date { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
