//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Rental_Tri.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int User_ID { get; set; }
        public string Full_Name { get; set; }
        public string Email_Address { get; set; }
        public string Password { get; set; }
    }
}
